### ISSUE TITLE
API should have the ability to not touch the filesystem

### ISSUE THREAD

**Issue by fresheneesz** [quentinrossetti/node-7z#1]
I've come to understand that pretty much no module should be reading the filesystem directly. The reason is because is severely limits its practicality and/or efficiency. For example, what if you're downloading the file from the internet? There may be no reason to save it to disk, rather you might want to use a stream. 

So I'm recommending that this module be amended to support streams and regular strings in addition to filenames.

**Comment by quentinrossetti** [comment]
The abilty to compress/decompress a stream using LZMA is not the goal of this package.
See [lzma-native](https://www.npmjs.com/package/lzma-native) instead.
