### ISSUE TITLE
err Error: spawn 7z ENOENT ？Why?

### ISSUE THREAD

**Issue by glk-hll** [quentinrossetti/node-7z#101]

**Comment by Jmopel** [comment]
Please read the [Installation](https://github.com/quentinrossetti/node-7z#installation) section.
> You should have the a 7-Zip executable (v16.02 or greater) available in your system.
> An alternative is to add the `7zip-bin` module to your project.

**Comment by glk-hll** [comment]
thanks, But i use `7zip-bin`  the following error occurred after packing
![image](https://user-images.githubusercontent.com/44257305/122886743-cd5ba580-d372-11eb-9bb4-ee2b25d7b1a0.png)

How to solve this problem? ☺

**Comment by quentinrossetti** [comment]
Hello. Please post the relevant part of your code.

**Comment by pixelastic** [comment]
Could you also share which OS you're running this on? I had similar issues and I think I fixed it by replacing `app.asar` with `app.asar.unpacked` but I'm not exactly remember what the root issue was.

**Comment by glk-hll** [comment]
My system is windows 64bit . @pixelastic The problem is solved, but it's not elegant enough. I use it `app.asar.unpacked\\node_modules\\7zip-bin\\win\\x64\\7za.exe`  , passing it to the `$bin` parameter of `extractfull`. 

Before that, the `path7za` with the value of `7zip bin` passed to `$bin` reported my initial error.

**Comment by quentinrossetti** [comment]
Check the installation https://github.com/quentinrossetti/node-7z#installation snippet, it is what your are doing but with a more "elegant" syntax.
