### ISSUE TITLE
Empty string used for password with `password: null | undefined` passed

### ISSUE THREAD

**Issue by pixelastic** [quentinrossetti/node-7z#102]
Hello,

It seems like calling `Seven.add('file.zip', ['file.txt'], { password: null })` creates a password-protected zip (I'm not sure what actual password is set, if it's an empty string or something else).

I tried with `password: undefined` as well but it seems that as soon as a `password` key is defined in the options, it triggers the behavior.

Tried with 7z from the `7zip-bin` package on Ubuntu (so, 7zip version 16)

My workaround is to `delete` the `password` key if it's set before passing it to `Seven`

**Comment by quentinrossetti** [comment]
Hi,

I added a check for those cases, it will be in the next release.

However I strongly recommend against passing options with *falsy* values for any switch that is not a boolean. It can trigger weird behaviors with the 7-Zip CLI. Also read https://github.com/quentinrossetti/node-7z#security
