### ISSUE TITLE
Quickest way to determine number of files in the archive

### ISSUE THREAD

**Issue by rishighan** [quentinrossetti/node-7z#108]
Hello, is the only way to determine the count of the files in the archive:

1. Listing the files and counting them or
2. Extracting them and counting them similar to the method described [here](https://github.com/quentinrossetti/node-7z/issues/35#issue-197883030) ?

**Comment by quentinrossetti** [comment]
Hello,
In my opinion it would be (1) to list and count.
Extract would write to the disk and that can be slow.
Happy coding!
