### ISSUE TITLE
How to read files data without extracting it.

### ISSUE THREAD

**Issue by pawanjangid** [quentinrossetti/node-7z#127]
Can you help me with that.. I want to read all files data in function itself and need to do some processing with data the data.

**Comment by kshitijkurandwad211** [comment]
I don't think you can do that using this library, According to me the main reason this library exist is to unzip/zip files using 7-zip. This is just a wrapper written to run command line functions (they do using childProcess()) and give the output.

**Comment by twok020101** [comment]
I don't think you can do that using this library, According to me the main reason this library exist is to unzip/zip files using 7-zip. This is just a wrapper written to run command line functions (they do using childProcess()) and give the output.

**Comment by c2iarx** [comment]
Lovely But After some work I did export to local storage(tmp)_ on lambda function and read file one by one and extract process and delete the files it works very well..
THanks.

**Comment by pawanjangid** [comment]
Lovely But After some work I did export to local storage(tmp)_ on lambda function and read file one by one and extract process and delete the files it works very well..
THanks.
