### ISSUE TITLE
Wildcards problem

### ISSUE THREAD

**Issue by sevenskull** [quentinrossetti/node-7z#13]
I found a problem which if I pass more than one value in wildcards, it doesn't work.
For example, if i want to extract selected files
wildcards: [ 'test.txt' ]
This above, works, but the below option doesn't.
wildcards: [ 'test.txt', 'test2.txt' ]

So i've made a change to make it work for me:
util/switches.js in line 38:

Before:

``` javascript
if (s === 'wildcards') {
     a.unshift(switches.wildcards);
}
```

After:

``` javascript
if (s === 'wildcards') {
     switches.wildcards.forEach(function(wildvalue, index){ a.unshift(wildvalue); });
}
```

**Comment by quentinrossetti** [comment]
Closed in `v1.0.0`
Check the README to adapt your code to the new API
