### ISSUE TITLE
Error: spawn 7z ENOENT

### ISSUE THREAD

**Issue by brickyang** [quentinrossetti/node-7z#17]
I want to use node-7z on CentOS. I have tested my app on Mac and it works. When I ran the app on server, it throws an error about

```
Error: spawn 7z ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickDomainCallback (node.js:405:17)
```

I saw this error once on my Mac. The reason for that is I forgot to install 7z on Mac. So I suppose this error stated the module can't find 7z command but I have already installed 7zip from http://netix.dl.sourceforge.net/project/p7zip/p7zip/15.09/p7zip_15.09_src_all.tar.bz2 and set the `$PATH` and alias in `~/.bashrc`:

```
export PATH=/data/node/mongodb/bin:/usr/local/bin/:$PATH
alias 7z='7za'
```

I can run `7z a` command on shell.

The path of 7z is `/usr/local/bin/7za`.

**Comment by brickyang** [comment]
Finally I resolved this problem by installing `p7zip-plugin`

**Comment by davidpharrington** [comment]
appears to be named p7zip at this point
