### ISSUE TITLE
can i pipe the result of mytask.add api to the response object?

### ISSUE THREAD

**Issue by manishcalling** [quentinrossetti/node-7z#22]
mytask.add('c:/test.7z', 'c:/test.txt', { p: 'manish' })
              .then(function () {
                console.log('Adding file to zip done 2!');
               });

I need to pipe the created test.7z to the response object.

**Comment by quentinrossetti** [comment]
Yeah this is not currently possible. But I am working on a major revision that will implement streams, unix stuff, more options, etc.
