### ISSUE TITLE
Error while creating the zip on ubuntu and windows? 

### ISSUE THREAD

**Issue by manishcalling** [quentinrossetti/node-7z#24]
Hi,

I created a small app to be deployed on bluemix. I needed to download the ubuntu package and integrate with my nodejs app. I also set the path to the bin directory. but then I get the below error

2016-04-14T12:45:09.38+0100 [App/0]      ERR     Potentially unhandled rejection
 [2] undefined (WARNING: non-Error used)

Here is my code:-
	var express = require('express');
	var fs = require('fs');
	var path  = require('path');
	var cfenv = require('cfenv');
	var envPath = __dirname;
	if (envPath.indexOf('7z') < 0) {
		var _7zipPath = path.join(process.cwd(), '/bin');
		process.env.PATH += (envPath[envPath.length -1] === ';') ? _7zipPath : ';' + _7zipPath;
	}
    var Zip = require('node-7z');
	var archive = new Zip();
	archive.add("/home/vcap/app/archive.zip", "/home/vcap/app/README.md", {p: "manish"}).then(function () {
	});

Also below is the structure of my directory

![3bc1c96b95ad0710](https://cloud.githubusercontent.com/assets/18337685/14527159/e8411204-023f-11e6-8073-be7dc1727a8e.png)

Any help is appreciated

**Comment by quentinrossetti** [comment]
hi manish,
i don't have enough info on the error to help you
an good way to find where the bug is coming from is to use `node-inspector`
i encourage you to try this and come back here if you still need help

Quentin Rossetti
<quentin.rossetti@gmail.com>

2016-04-14 15:47 GMT+02:00 manishcalling <notifications@github.com>:

**Comment by quentinrossetti** [comment]
hi manish,
i don't have enough info on the error to help you
an good way to find where the bug is coming from is to use `node-inspector`
i encourage you to try this and come back here if you still need help

**Comment by manishcalling** [comment]
Hi Quentin,

I was able to resole it by installing the shell along with the application.
Thanks for your replies..
