### ISSUE TITLE
Error: spawn 7z ENOENT

### ISSUE THREAD

**Issue by nrnaveen0492** [quentinrossetti/node-7z#25]
events.js:154
      throw er; // Unhandled 'error' event

Error: spawn 7z ENOENT
  at exports._errnoException (util.js:890:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
  at onErrorNT (internal/child_process.js:348:16)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by lbeschastny** [comment]
Looks like you don't have `7z` executable in your `PATH`, [see README for more details](https://github.com/quentinrossetti/node-7z#installation).

**Comment by quentinrossetti** [comment]
Hi, a bug report should be more than just a copy-paste of you stdout.
check [this page](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
also using the search function you can find this #17

**Comment by yunnysunny** [comment]
I have install p7zip in my centos, and the p7 command in the $PATH, but the same error occured.

**Comment by quentinrossetti** [comment]
Hi,
By default the module will use the `7z` in your $PATH (I'v noticed that you have a `p7` command, is that a typo?)
Make sure that you've followed the installation process https://github.com/quentinrossetti/node-7z#installation

**Comment by yunnysunny** [comment]
> Hi,
> By default the module will use the `7z` in your $PATH (I'v noticed that you have a `p7` command, is that a typo?)
> Make sure that you've followed the installation process https://github.com/quentinrossetti/node-7z#installation

Yes, I mean 7z command exists in my $PATH.

**Comment by quentinrossetti** [comment]
Try installing this:
https://github.com/quentinrossetti/node-7z/issues/17#issuecomment-173089317
And tell us if works for you.

If not please provide more information Like:
- OS
- NodeJS version
- Package version
- 7Zip version
- The portion of your code where you are using this module
