### ISSUE TITLE
The list command assumes there will be digits in the Compressed Column

### ISSUE THREAD

**Issue by Rich-amoebaWare** [quentinrossetti/node-7z#26]
I have a .cbr (.rar) file that has the following output when the list command is called:

   Date      Time    Attr         Size   Compressed  Name

---

2015-03-22 08:17:19 D....            0            0  Accident
2013-03-08 11:12:12 ....A       255286      5945700  Accident/001.jpg
2013-03-08 11:12:12 ....A       259421               Accident/002.jpg
2013-03-08 11:12:12 ....A       221211               Accident/003.jpg
2013-03-08 11:12:12 ....A       173991               Accident/004.jpg

.... + 21 more files...

This archive (for whatever reason) does not display the compressed size of each file. Instead it displays the total compressed size of the archive in the first file's Compressed column.

This causes the list command to only return an array containing two items: the folder and the first file.

By changing the regex var in the lib/list.js module 
to:
    var regex = /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) ([.DA]+) +([\d\s]+) +\d+ +(.+)/;
from:
    var regex = /(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) ([.DA]+) +(\d+) +\d+ +(.+)/;

to tell it to look for one or more digits or spaces... 

The code now returns the complete list of 25 files. It also works for archives which have digits in the Compressed column.

**Comment by shea-sollars** [comment]
I wish I would have seen this sooner.

**Comment by quentinrossetti** [comment]
Closed in `v1.0.0`
Check the README to adapt your code to the new API
