### ISSUE TITLE
Extract/Extract full few files in 7z archive

### ISSUE THREAD

**Issue by aco7342** [quentinrossetti/node-7z#3]
i need some help to make extract/extract full with filename  or fileext filter.

i try use { p: '*.png}, and { ax : '*.png'} for exclude files,  but not work., ref 7zip api document

**Comment by quentinrossetti** [comment]
now you can use the `wildcards` attributes in the options. also do not forget the `*` when specify a wildcard. 

`7z a -tzip archive.zip *.txt -x!temp.*
adds to the archive archive.zip all *.txt files, except temp.* files.
becomes : 
```js
sevenzip.add('archive.zip', '*.txt', {
  t: 'zip',
  x: '!temp.*'
})
```
http://7zip.bugaco.com/7zip/MANUAL/switches/exclude.htm
