### ISSUE TITLE
Unsupported Method

### ISSUE THREAD

**Issue by warlord0** [quentinrossetti/node-7z#33]
When trying to use it with a zip file created using some "unknown" program the 7z extract seems to succeed but returns the filename in .progress() in the form:

```text
The Punisher (2016-) 001-000.jpg     Unsupported Method
```

Which is from the direct output from 7z x
```text
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: The Punisher 001 (2016) (digital) (Oroboros-DCP).cbr

Extracting  The Punisher (2016-) 001-000.jpg     Unsupported Method
Extracting  The Punisher (2016-) 001-001.jpg     Unsupported Method
Extracting  The Punisher (2016-) 001-002.jpg     Unsupported Method
Extracting  The Punisher (2016-) 001-003.jpg     Unsupported Method
Extracting  The Punisher (2016-) 001-004.jpg     Unsupported Method
```

Is there any way it could trigger an error to be handled with .catch()?

**Comment by quentinrossetti** [comment]
hi,
i implemented the behaviour in the `extract` and `extractFull` methods. does the `Unsupported Method` appear on other methods (list, test, add...) ?
also could you send me a tiny file that triggers this error so i can add this to the tests ?

**Comment by jloqfjgk** [comment]
That's a .cbr file, which means it is actually a RAR file.

If it is a ZIP file, it would have been named .cbz instead.
