### ISSUE TITLE
Version of 7z.exe must be v9.XX

### ISSUE THREAD

**Issue by warlord0** [quentinrossetti/node-7z#34]
I spent a few hours wondering why this worked just fine on my Linux system but failed on Windows.

On windows it returned no files having been extracted even though when I looked at the output folder there they were.

Turned out I have 7z.exe v16.04 on the windows machine. The v15.XX and up do not report their progress to stdout like v9.XX as "Extracting " so the 7z succeeds, but node-7z module is unable to capture the list of extracting files from stdout.

Not really an error as such, but thought it may be worth adding into the readme.

**Comment by quentinrossetti** [comment]
hi,
i don't have a windows machine available right now. could you copy-paste the outputs of your extraction using v9.XX and v>=15.XX ?

**Comment by MichaelFroeschen** [comment]
The switch -bb1 has to be set in order for the progress to work.
Without the switch, 7-Zip shows a single line in the cli, that updates itself based on the current progress.
With the switch, every processed file is shown.

From the changelog:

> 15.05 beta     2015-06-14
>   (...)
> -Console version now shows names of processed files only in progress line by default.
> -new -bb[0-3] switch to set output log level. -bb1 shows names of processed files in log.

**Comment by quentinrossetti** [comment]
Closed in `v1.0.0`
Check the README to adapt your code to the new API
