### ISSUE TITLE
the module shows FileSystemProvider: Invalid name:

### ISSUE THREAD

**Issue by emazzu** [quentinrossetti/node-7z#36]
Hi, how are you ?

I have this code on node, it works good, but before the End 7zip, show: FileSystemProvider: Invalid name:

do you know why ??

The module is still in development, can I use it without problem ?

Regards
Eduardo

/*
			probando 7-Zip
		*/
		var archives  = new Zip();
		archives.add('archives.7z', ['../storage/nah1/vol2/115000/Anexo A.PDF'], {
			m0: '=BCJ',
			m1: '=LZMA:d=21'
		})
			.then(function () {
				console.log("End 7zip.");
			// Do stuff... 
		});

**Comment by emazzu** [comment]
Hi, this message FileSystemProvider: Invalid name:, It was my mistake.

this question only ? The module is still in development, can I use it without problem ??

**Comment by quentinrossetti** [comment]
the module is currently in version 0.4.0, meaning it's not stable. I do no recommend using it in a production environnement. 
it's just a personal tool that i think i worth sharing.
