### ISSUE TITLE
Hangs on encrypted archive without supplied password

### ISSUE THREAD

**Issue by trymbill** [quentinrossetti/node-7z#37]
I'm not sure if this is an issue with this package or if 7z simply doesn't support this but from time to time I get archives with passwords that I don't have (i.e. I don't have the password for the archive). When I try to either test or extract one of those archives node-7z simply hangs instead of failing gracefully.

Is there a way to implement this or do you know of a way to check wether or not an archive is password protected before running it through node-7z?

**Comment by quentinrossetti** [comment]
Hi,
Could you try those archives with the `7z` command line tool directly to see if it's a `node-7z` or a `7-zip` related issue ?

**Comment by trymbill** [comment]
Using example password protected archive from http://www.philippwinterberg.com/software/rar_faq_encrypted_password_protected_secured_files.php

7z just hangs on waiting for password to be typed. I'm guessing that's what node-7z is waiting for. I can't see an option that ignores passwords and just exists. -y at least doesn't seem to do the trick.

```
$ 7z x -y example_password_protected.rar

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs x64)

Scanning the drive for archives:
1 file, 5374933 bytes (5249 KiB)

Extracting archive: example_password_protected.rar
--
Path = example_password_protected.rar
Type = Rar
Physical Size = 5374933
Characteristics = Lock Recovery
Solid = -
Blocks = 1
Multivolume = -
Volumes = 1


Enter password (will not be echoed):
```

**Comment by mzehrer** [comment]
The only possible way would be to use the list function beforehand to check the encrypted attribute.
