### ISSUE TITLE
Can't test archive file integrity when it was created by a diffrent process and still open by it

### ISSUE THREAD

**Issue by pantchox** [quentinrossetti/node-7z#39]
as title mentions.
Using it in the command line with the options `{ssw: true,y:true,ssc: true}` 
same options in node does not work.

**Comment by quentinrossetti** [comment]
is there a chance it's a 7zip limitation ?
without more context i can't help

**Comment by pantchox** [comment]
as i said (maybe it was not clear) i tested it in the command line while the file was opened by the processed (i put a breakpoint before the test operation and went to the shell) and it worked, so i assume it is something related to the node wrapper.

**Comment by pantchox** [comment]
Also i did another test of running a different node script to run the test and it didn't work and the 7zip cli worked.

**Comment by pantchox** [comment]
And last not least i tested the node script on a different archive and it work so i assume my script is not faulty.

**Comment by quentinrossetti** [comment]
well, i have honestly no idea...

**Comment by pantchox** [comment]
would you like me to create a code that makes this happen? how do we solve this because this is the only zip file integrity checker i found for node.

**Comment by quentinrossetti** [comment]
yes it would be very useful.
i know that there aren't many 7-Zip npm packages, that's the very reason i started writing my own.
