### ISSUE TITLE
version 0.3.0. wildcards #3

### ISSUE THREAD

**Issue by aco7342** [quentinrossetti/node-7z#4]
quentin, thanks a lot.
but 
this    .... wildcards: [ '*.txt', '*.md' ] ...    don't work.
this    .... wildcards: '*.txt' ....                  work for me.

**Comment by quentinrossetti** [comment]
you do have to use an `*` in your wildcards.

`.txt` will match a file that is named `.txt` and nothing else, that's how 7zip works.
