### ISSUE TITLE
not able to get proper error in case of corrupted zip file

### ISSUE THREAD

**Issue by baloda** [quentinrossetti/node-7z#41]
when i am using 7z as command for unzip file i am getting error message:

resident_image.png CRC Failed in encrypted file. Wrong password?,data.json

but using node-7z module, it is calling error catch with error undefined so and i got the zip extracted
so at run time its difficult to know extraction status.

i got zip extracted so it worked for me but with patch of error undefined

**Comment by quentinrossetti** [comment]
Closed in `v1.0.0`
Check the README to adapt your code to the new API
