### ISSUE TITLE
Zip.add() with empty file list cause add full working directory to zip file

### ISSUE THREAD

**Issue by Menci** [quentinrossetti/node-7z#43]
The 7z command line will be

```
/usr/lib/p7zip/7z a /home/syzoj/syzoj/uploads/testdata/312312354.zip -ssc -y
```

**Comment by AbdelghaniTassi** [comment]
can i work on this bug ?

**Comment by AbdelghaniTassi** [comment]
How do you call add function ?
can you post a piece of code ?

**Comment by AbdelghaniTassi** [comment]
A test should be added if the file list is empty 7z should not be called

**Comment by AbdelghaniTassi** [comment]
#44 fixed here
pull request still need to be validated

**Comment by quentinrossetti** [comment]
@Menci what are you trying to achieve ?
I think it's the default behaviour of 7-zip
