### ISSUE TITLE
Moved project to another computer and extractFull method throws an error

### ISSUE THREAD

**Issue by HarounAns** [quentinrossetti/node-7z#49]
I am running into a strange error and wonder if anyone can help me. 

I moved my project to another computer, the entire file structure with the 7z.exe included in it. I also copied my node-modules folder containing the node-7z folder in it. However when my code tries to extract it does not work it throws an error but when it tries to catch it, the error is undefined. I tried with using the 7z.exe itself and it did the job correctly, it is just the code that does not used the extractFull method correctly, although it was working correctly on my old computer. Any help would be appreciated!

**Comment by HarounAns** [comment]
I realize that it is a problem with only including the .exe and not the other files, because I got the cant load the module: 7z.dll error. I downloaded the entire 7zip file with the 7zip.dll and am getting the same error. Any ideas?

**Comment by quentinrossetti** [comment]
Closed in `v1.0.0`
Check the README to adapt your code to the new API
