### ISSUE TITLE
Allow to specify custom paths to all the binaries so it can be used in Electron apps (.asar)

### ISSUE THREAD

**Issue by AlexSHoffman** [quentinrossetti/node-7z#55]
Right now, when you try to use it in an Electron app you get this error:

```
Error: spawn 
E:\project-name\node_modules\electron\dist\resources\electron.asar\binaries\win32\7za 
ENOENT
```

This happens because `electron.asar` breaks relative paths.

Could you please allow to specify custom paths to all the needed binaries so it can be used in Electron apps (.asar)?

**Comment by AlexSHoffman** [comment]
Looks like it's been done in [es-7z](https://www.npmjs.com/package/es-7z) module. But it's no longer maintained.

**Comment by quentinrossetti** [comment]
Hi. It is a popular request and has been added to the master branch.

If you need this feature right now 7784630  is a working version (README not up-to-date but check out the tests for usage. 
WARNING
Right now i'm working on the API, so expect breaking changes in the nearby future.

**Comment by AlexSHoffman** [comment]
@quentinrossetti thanks mate!

**Comment by quentinrossetti** [comment]
Closed in `v1.0.0`
Check the README to adapt your code to the new API

**Comment by AlexSHoffman** [comment]
@quentinrossetti good job! 

I found a problem though:

Importing this module in a Electron-Webpack project results in the following error:

```
Uncaught TypeError: Cannot destructure property `dir` of 'undefined' or 'null'.
```

P.S. 
I Tried importing it in a project based [on this](https://github.com/nklayman/vue-cli-plugin-electron-builder) Electron-Webpack-Vue boilerplace

**Comment by AlexSHoffman** [comment]
@quentinrossetti good job! 

I found a problem though:
Importing this module in a Electron-Webpack project results in the following error:

```
Uncaught TypeError: Cannot destructure property `dir` of 'undefined' or 'null'.
```
![image](https://user-images.githubusercontent.com/13764106/49550609-3d14fc80-f8fd-11e8-90a1-0bc1aa16f1c9.png)

Any ideas on why that might be happening?

Do you think this might be related to this?:
https://github.com/standard-things/esm/issues/97#issuecomment-439717584

I Tried importing it in a project based [on this](https://github.com/nklayman/vue-cli-plugin-electron-builder) Electron-Webpack-Vue boilerplate.

But it looks like it DOES seem to be working in [this](https://github.com/electron-userland/electron-webpack-quick-start) Electron-Webpack boilerplate.
