### ISSUE TITLE
Problems with typescript

### ISSUE THREAD

**Issue by mateoc10** [quentinrossetti/node-7z#58]
I'm having trouble using this with typescript.
I had to do some changes in the way to include it but after being able to import everything it fails when I try to use it.

```
import Seven = require('node-7z');
import { path7za } from '7zip-bin'

const seven = new Seven();
const stream = seven.extractFull(
            './example.7z',
            './',
            {
                $bin: path7za
            }
        ).then(resp => {
            console.log('finish', resp);
        })
```

Error in (undefined) /node-7z/src/flags.js
Module parse failed: node_modules/node-7z/src/flags.js Unexpected token (9:15)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (9:15)
 @ ./~/node-7z/src/main.js 4:14-32

Error in (undefined) /node-7z/src/commands.js
Module parse failed: node_modules/node-7z/src/commands.js Unexpected token (2:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:10)
 @ ./~/node-7z/src/main.js 10:17-38

Thanks for the help

**Comment by mateoc10** [comment]
I added the new Seven() line because if I don't add it it says: Property 'extractFull' does not exist on type 'typeof Zip'

**Comment by quentinrossetti** [comment]
Hi. I'm not familiar with TypeScript but I see that the usage is not correct. You tried to call `then()` on a stream.
Try this:
```js
const seven = new Seven();
const stream = seven.extractFull(
            './example.7z',
            './',
            {
                $bin: path7za
            }
        ).on('end', resp => {
            console.log('finish', resp);
        })
```
Let me know if it helps
