### ISSUE TITLE
[question] list doesn' work

### ISSUE THREAD

**Issue by hjyssg** [quentinrossetti/node-7z#59]
```js
const _7z = require('node-7z');
const myStream = _7z.list('C:\\Downloads.zip',  
                                          { recursive: true, "$cherryPick": ['*.txt*', '*.js'] });
const _data = [];
myStream
.on('data', function(d){
	console.log(d);
	_data.push(d);
})
.on('end', function (d) {
  	console.log("end", _data);
  	res.send({_data, info: myStream.info});
}).on('error', function (d) {
  	console.log("error:", d);
  	res.send(d);
})
```

Excuse me, could you take a look?
I can see a pop console windows, it shows the content. But the data is empty.
When I run the _7z.extractFull, it extracts the file. But the console data does not goes to data either.

**Comment by quentinrossetti** [comment]
Hi,
First thing is to check your version of 7zip, it must be v16.02 or greater.

I've just run your code in the test suite:
![image](https://user-images.githubusercontent.com/805805/51430825-b43df000-1c20-11e9-90e9-9f5a44f6dd79.png)
And it works fine on OSX. 
![image](https://user-images.githubusercontent.com/805805/51430832-d33c8200-1c20-11e9-86fb-baaf5c9ed202.png)

**Comment by hjyssg** [comment]
Thank you very much. I  used 7zip-bin from npm and I runs on Windows10. 
I also run the test, it failed on my machine.

```js 
//anywhere, here is my solution
const { spawn } = require('child-process-promise');
const getList = spawn(sevenZip, ['l', '-ba', fileName], { capture: ['stdout', 'stderr'] });
getList.then((data) => {
    // parse 7zip output
    const text = data.stdout;
 });

Thanks
