### ISSUE TITLE
zip blob with password

### ISSUE THREAD

**Issue by DanRic** [quentinrossetti/node-7z#63]
Hi, 
I'm working with Angular (typescript).
How I can create zip with password passing Blob object or string, using Seven.add?
const myStream = Seven.add('Files.7z', '*.txt', {
  recursive: true
})

I don't want to use files on local paths

**Comment by quentinrossetti** [comment]
Hi,

It seems that there are several questions here.

7-Zip accepts passwords as string. With this module you can:
```js
const myStream = Seven.add('Files.7z', '*.txt', {
    recursive: true,
    password: 'super duper secret!'
})
```

For the Blob thing. If I understand you have a Blob object that you want to compress without writing it on the file system? Maybe the `fromStdin` option is part of the solution (see https://sevenzip.osdn.jp/chm/cmdline/switches/stdin.htm). This will require some further digging, can you provide a more complete portion of code to better see what you are trying to do?

For the Angular part: What is you development environment (Angular on Electron?).

Tell me if it helps!

**Comment by DanRic** [comment]
Thanks for the answers.
I'm working in Angular environment.
I am watching Stdin, but I have not yet figured out how to use it with local variables of blob types.

**Comment by quentinrossetti** [comment]
After some testing here is how to use `fromStdin` option
```js
const archive = `archive-to-create.7z`
const source = require('fs').createReadStream(`file-to-compress.txt`) 
const seven = Seven.add(archive, '', { // leave second argument emtpy
  fromStdin: 'public-name.txt', // you can rename 'file-to-compress.txt'
                                // here, if you want. otherwise leave empty an string
})    
source.pipe(seven._childProcess.stdin)
seven.on('end', function () {
  // do stuff
})
```
What is important is that `source` can be *in theory* any [Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable) stream.

**Comment by quentinrossetti** [comment]
I know people do crazy amazing stuff with JS these days, but I have trouble seeing what exactly you are trying to achieve (hence my question on your environment)

As far as I know Angular and Blob are in the browser, but you need to `spawn` a child process and have a `7z` executable on your machine in order for this module to work.

Am I missing something?
