### ISSUE TITLE
Why I cant use 7za in linux environment

### ISSUE THREAD

**Issue by bilibiliou** [quentinrossetti/node-7z#65]
report: spawn 7z error

**Comment by bilibiliou** [comment]
I think u should support both 7za and 7z

**Comment by bilibiliou** [comment]
I solve by make a soft link:
sudo ln -s /usr/bin/7za /usr/bin/7z

**Comment by bilibiliou** [comment]
However I think the project must support command **"7za"** on linux environment

**Comment by quentinrossetti** [comment]
Hello,
7za is supported, the "good" way of doing this is simply like this.
```js
const seven = extractFull('./archive.7z', './output/dir/', {
  $bin: '7za'
})
```
Also words like "hello", "hi", "I need help with...", and "thank you" are permitted when interacting with other human beings...
Have a nice day

**Comment by bilibiliou** [comment]
nice work thx for your support
