### ISSUE TITLE
Error when installing: p7zip-16.02 returns 14615 segmentation fault

### ISSUE THREAD

**Issue by luisnomad** [quentinrossetti/node-7z#66]
Hi all. I am using node v10.15.3 and npm v6.9.0 on Mac OS Mojave 10.14.5

I am trying to use node-7z-forall, but when the module is installing I get this error:

```
Error: Error: Command failed: /Users/luisnomad/Projects/personal/7ztozip/node_modules/all-unpacker/unar "/Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/p7zip-16.02.pkg" -o /Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/darwin -f -D

    at /Users/luisnomad/Projects/personal/7ztozip/node_modules/all-unpacker/index.js:45:40
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm WARN 7ztozip@1.0.0 No description
npm WARN 7ztozip@1.0.0 No repository field.

```

I've tried running the failing command separately:

`/Users/luisnomad/Projects/personal/7ztozip/node_modules/all-unpacker/unar "/Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/p7zip-16.02.pkg" -o /Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/darwin -f -D
`

the output is:

`/Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/p7zip-16.02.pkg: [1]    14578 segmentation fault  /Users/luisnomad/Projects/personal/7ztozip/node_modules/all-unpacker/unar  -o`

Since the binary is not successfully installed, I get this error when doing **extractFull**:

```
{ Error: spawn /Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/binaries/darwin/7za ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall:
   'spawn /Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/binaries/darwin/7za',
  path:
   '/Users/luisnomad/Projects/personal/7ztozip/node_modules/node-7z-forall/binaries/darwin/7za',
  spawnargs:
   [ 'x',
     '/Users/luisnomad/Projects/personal/7ztozip/AI Shougi 3.7z',
     '-o/Users/luisnomad/Projects/personal/7ztozip/temp',
     '-$bin/Users/luisnomad/Projects/personal/7ztozip/node_modules/7zip-bin/mac/7za',
     '-ssc',
     '-y',
     '-bb2' ] }
```

I have 7z installed on my machine but it doesn't seem to try using it.

Any ideas?

**Comment by quentinrossetti** [comment]
Hi !

The package `node-7z-forall` was forked by @techno-express about 10 months ago and seems no longer maintained. This fork was based on an old version (pre v1.0.0) of `node-7z` So if you are not in the right place, sorry.

Since v1.0.0 the API has changed so you want to update your code.
The https://github.com/quentinrossetti/node-7z#installation presents a clean way to embed 7-Zip binaries in you project.

I close this issue but feel free to ask any question you may have.

**Comment by techno-express** [comment]
The issue has been resolved. The download link for the Linux binary was changed.
