### ISSUE TITLE
Opens command prompt and logs everything there instead of error or progress

### ISSUE THREAD

**Issue by talhaanees** [quentinrossetti/node-7z#67]
Hi,

I am able to successfully extract a .7z file. However, I cannot seem to capture any error, progress or data, as the spawn command opens everything in a separate cmd window.

`extract7z_stream = Seven.extractFull(filePath, outputPath, {
        $progress: true
    });
    extract7z_stream.on('error', (err) => {
        console.log(err, " in extraction 7zip");
    });
    extract7z_stream.on('end', () => {
        console.log("all done")
    });
    extract7z_stream.on('progress', (progress) => {
        console.log(progress);
    });`

**Expected Behavior: ** See everything in dev tools window.

**Current Behavior: ** Opens command prompt window and stdouts everything there. 
As shown in the image.
![cmd_out](https://user-images.githubusercontent.com/14168151/59844581-f2704480-9363-11e9-9f95-cb1500b9a4e5.PNG)

*Edit: Any help would be appreciated. Thank-you.

**Comment by quentinrossetti** [comment]
Hi,
It seems to be a Windows only problem. Please post the version of Windows, 7-Zip and node-7z and workflow (is it a PowerShell windows I see in the background ?) you are using ?
So far I can't reproduce the bug on my Windows VM.

For future me: Maybe check https://github.com/quentinrossetti/node-7z/blob/51e3cf084b68525a4bb7ea689798c29669e2a415/src/lifecycle.js#L56

**Comment by quentinrossetti** [comment]
I mark this issue as stale. Feel free to reopen if you have additionnal data to provide.
