### ISSUE TITLE
remove polyfill

### ISSUE THREAD

**Issue by m59peacemaker** [quentinrossetti/node-7z#69]
I was unable to use this package due to its use of a polyfill. It somehow conflicted with Meteor and caused the app to be unable to run. I forked it and replaced the polyfill with a local reference that serves the same purpose, via this:

```
const RegExp = (() => {
	try {
		new RegExp('(?<test>a)')
		return RegExp
	} catch (error) {
		return require('named-regexp-groups')
	}
})()
```

Would you accept that as a PR?

**Comment by quentinrossetti** [comment]
Hi, 

If I understand correctly just replacing the current `regex-polyfill` by `named-regexp-groups` and removing the check on NodeJS versions in https://github.com/quentinrossetti/node-7z/blob/master/src/regexp.js will make it work for you?

That's a elegant solution and I would accept this PR given some conditions :
- Make sure that the try/catch doesn't runs once, and not a every match
- https://github.com/quentinrossetti/node-7z/blob/master/CONTRIBUTING.md

I intend to drop the polyfill hack in January 2020.

**Comment by m59peacemaker** [comment]
@quentinrossetti It would not run every match. That function is executed immediately where it is declared, to dynamically set the value of `RegExp`. It is logically the same as this:

```js
try {
	new RegExp('(?<test>a)')
} catch (error) {
	RegExp = require('named-regexp-groups')
}
```

But I find setting a value that way unpleasant.

**Comment by quentinrossetti** [comment]
The polyfill is removed as of v2.0.3.
Support fore Node.JS v8 is dropped too.
