### ISSUE TITLE
Doesn't support the default version of p7zip in Ubuntu 16.04

### ISSUE THREAD

**Issue by mredbishop** [quentinrossetti/node-7z#71]
The logLevel flag doesn't exist in 9.2 so this blows up when using it with 7z on Ubuntu 16.04 for most  deployments. There needs to be a way to exclude the log level I think?

**Comment by quentinrossetti** [comment]
Hi,
I tried to make this module work with older versions of 7-Zip (pre 15.xx) without success.
The good news for you is that there is also an older version of this module that was written for those older versions of 7-Zip. 
Check : https://github.com/quentinrossetti/node-7z/releases/tag/v0.3.0
As it was released on npm you can use this version in your `package.json`.
Note that the usage was different back then, but you can check the README for documentation.
