### ISSUE TITLE
engine requires node >= 10

### ISSUE THREAD

**Issue by UncleBill** [quentinrossetti/node-7z#73]
https://github.com/quentinrossetti/node-7z/blob/e1418e10e5086c4db7295277bbd12f9bc9410d6e/src/regexp.js#L16-L22

Since above code uses [`Named capture groups`][1] which was introduced since node 10.

see: https://runkit.com/embed/647oxgaaw7p4 (run on node 8)

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility

**Comment by quentinrossetti** [comment]
Hi, It's a design choice made (a bit to soon maybe?) to fit NodeJS support. (1)
For legacy application running NodeJS v8 you can still use a slightly older version. (2)
`npm i node-7z@1.1.1`
(1) https://nodejs.org/en/about/releases/
(2) https://github.com/quentinrossetti/node-7z/blob/master/CHANGELOG.md#200-2019-10-27

**Comment by UncleBill** [comment]
Hey there, I meant you should add `engines` field to package.json to notify users who are using `node < 10` in `npm install` phase.

https://docs.npmjs.com/files/package.json#engines

**Comment by quentinrossetti** [comment]
That is a clean fix, I forgot that you can do that. Definitely going in the next release.

**Comment by quentinrossetti** [comment]
Fixed on `node-7z@2.0.5`. 
(1) Commit 4e43f90c6e08a1bbde9e788f5ebf51d9e1fffd45
