### ISSUE TITLE
changing the cwd

### ISSUE THREAD

**Issue by Ladvace** [quentinrossetti/node-7z#75]
Is there any way to change the cwd?

**Comment by quentinrossetti** [comment]
Hi. Currently no. But it would be easy to implement. I'm working on it!

**Comment by Ladvace** [comment]
Is there any wait in the mainwhile to workaround It, honestly i didnt font
anything also in the 7z doc

Il ven 14 feb 2020, 22:25 Quentin Rossetti <notifications@github.com> ha
scritto:

**Comment by quentinrossetti** [comment]
quick hack : in `src/lifecycle.js` edit :
```js
// add this at line 45
seven._spawnOptions = options.$spawnOptions
```
and
```js
// at line 70 replace all the function
const run = stream => {
  let spawnOptions = Object.assign({ detached: true }, stream._spawnOptions)
  stream._childProcess = spawn(stream._bin, stream._args, spawnOptions)
  return stream
}
```

now you do something like:
```js 
const pathTo7zip = sevenBin.path7za
const seven = extractFull('./archive.7z', './output/dir/', {
  $bin: pathTo7zip,
  $spawnOptions = { cwd: '/your/cwd' } 
})
```

**Comment by quentinrossetti** [comment]
You may also want to check https://sevenzip.osdn.jp/chm/cmdline/switches/working_dir.htm

**Comment by quentinrossetti** [comment]
Feature added and [documented](https://github.com/quentinrossetti/node-7z#special-options) in `node-7z@2.1.1`.

**Comment by Ladvace** [comment]
I read that page on 7z but this is not the cwd, this is a temporary path
