### ISSUE TITLE
Is it possible to read the rar/zip file from network stream (url)

### ISSUE THREAD

**Issue by manishrawat4u** [quentinrossetti/node-7z#76]
I am looking to read a network stream but it is throwing opening : Not implemented error

```
   const sevenStream = Seven.list(null, {
        recursive: true,
        $bin: pathTo7zip,
        // toStdout: true,
        fromStdin: ' test.zip'
    });
    
    sevenStream.on('end', function () {
        var sinfo = sevenStream.info;
    })

    sevenStream.on('error', function (err) {
        console.log(err);
    })
    var stdin = sevenStream._childProcess.stdin;
    var gotstream = got.stream(streamurl);    
    gotstream.pipe(stdin);
```

**Comment by quentinrossetti** [comment]
Hello,
7-Zip is not well suited for reading streams. Depending on the format of the archive I recommend the standard library https://nodejs.org/dist/latest-v12.x/docs/api/zlib.html

**Comment by quentinrossetti** [comment]
Hi, have you find a way to achieve your goal? Let me know.

**Comment by manishrawat4u** [comment]
No luck yet.. i found the way to handle zip but rar/7z are still mystery to me..

**Comment by quentinrossetti** [comment]
For 7z can you try with a command line like this https://sevenzip.osdn.jp/chm/cmdline/switches/stdin.htm ? 
I will also try on my side.

It's true that they are very different beasts (different algorithm, different programs). It would be nice to have a shared streaming program for common archives but I don't think it's will happen in the near future for the Node.JS community. Maybe through the XZ format?

That said: 
- for 7-Zip archives see https://www.npmjs.com/package/lzma-native. It's a more direct approach
- for RAR achives see https://serverfault.com/questions/115584/is-it-possible-to-stream-input-into-rar (it's for writing but there might be a option for reading)

**Comment by quentinrossetti** [comment]
Is was able to make the example from the official documentation to work.
With gzip `cat issue76.gz | 7z x -tgzip -si`
With xz `cat issue76.xz | 7z x -txz -si` 
But it didn't work with a `7z` archive. 

Note that `xz` and `7z` are equivalent (same algorithm) in both compress/decompress time and size. So if you can try using `xz` format.
