### ISSUE TITLE
Use 7z in 7za place

### ISSUE THREAD

**Issue by vanuatu** [quentinrossetti/node-7z#8]
I need unpack JDK8.exe but 7za.exe don't do the magic, then I need to use 7z.exe and 7z.dll... 

As a workaround I put 7z.dll and 7z.dll in my application root and rename the binary 7z.exe to 7za.exe

The solution works well , but a better solucion should be written

**Comment by Riuujin** [comment]
Thank needed to use the same workaround. Is there a specific reason that 7za is used instead of 7z?

**Comment by quentinrossetti** [comment]
Nop. Fixed in the next release
