### ISSUE TITLE
Missing switch -mx

### ISSUE THREAD

**Issue by patrickpissurno** [quentinrossetti/node-7z#80]
Hi! Nice work on this module.

I might have missed something, but I just can't find how to specify the following when using this module `-mx=9`

What I'm trying to do is set the compression level parameter. It seems to me that it is not yet supported (when looking at the source and docs). Could it be?

Thanks!

**Comment by quentinrossetti** [comment]
Hi, thanks for the compliment :)
I didn't test this specific test but it seem that you can use this https://github.com/quentinrossetti/node-7z#compression-method
So in your case:
```js
const compress = Seven.add('archive.7z', 'files_to_compress', {
  method: ['x=9']
})
```
Tell me if it works!
