### ISSUE TITLE
workingDir does not work (no pun intended)

### ISSUE THREAD

**Issue by markentingh** [quentinrossetti/node-7z#85]
when using the `add` method, I am setting the `workingDir` option to `/bin/publish` and setting `source` to `test` but when I open the 7z file for inspection, the zip folder structure is `bin/publish/test` when I was hoping to just see `test` as my root folder within the zip file. Am I doing something wrong?

**Comment by quentinrossetti** [comment]
The best advise I can give you is trying the figure out the correct **command line**.
https://sevenzip.osdn.jp/chm/cmdline/switches/working_dir.htm
(pun taken :smile:  )

**Comment by markentingh** [comment]
I basically had to generate the zip in `/bin/publish` to get it to build the folder structure i wanted as a workaround.

**Comment by quentinrossetti** [comment]
After reading the upstream documentation it seems that the working directory is just a temp directory.
So I guess your workaround is actually the correct way to do it.
