### ISSUE TITLE
Congratulations and question about Windows cmd

### ISSUE THREAD

**Issue by frederikhors** [quentinrossetti/node-7z#89]
Using your amazing pkg on Windows 10 with the below code is opening my cmd, why?

![image](https://user-images.githubusercontent.com/41120635/102676184-98408180-419c-11eb-8f98-64d0342f7acf.png)

```js
function tryMe() {
  const compress = Seven.add("myfolder", "myfolder")
}

**Comment by Jmopel** [comment]
Try to use `7zip-bin` module as `$bin` option. Everything will happen in the background.

```
npm i 7zip-bin
```

```js
const Seven = require('node-7z')
const sevenBin = require('7zip-bin')

const pathTo7zip = sevenBin.path7za

function tryMe() {
  const compress = Seven.add("myfolder", "myfolder", {
	  $bin: pathTo7zip
  })
}
```

**Comment by quentinrossetti** [comment]
Thanks !

The package works by spawning an actual 7zip command based on your input, the parse the output (stdout) and send the appropriate JS events.

So what you see is "normal"

Unfortunatly I'm a little bit unclear on the implementation of the Spawn command on Windows (linux user here 😁) and I don't know why it's not happening in the background by default. 

I will run more tests in the next few weeks.

**Comment by quentinrossetti** [comment]
If you don't need the process to be [detached](https://nodejs.org/docs/latest-v14.x/api/child_process.html#child_process_options_detached) you can do:
```js
function tryMe() {
  const compress = Seven.add("myfolder", "myfolder", { $spawnOptions: { detached: false } } )
}
```

An alternative is the `windowsHide` option should do the trick. But due to what seems to be an upstream bug it doesn't at the moment. moxystudio/node-cross-spawn#143
```js
function tryMe() {
  const compress = Seven.add("myfolder", "myfolder", { $spawnOptions: { windowsHide: true } } )
}
```

**Comment by quentinrossetti** [comment]
Note to myself : consider adding `windowsHide` as a default on the next verion

**Comment by quentinrossetti** [comment]
Fixed on the next release
