### ISSUE TITLE
is there a way to extract only the first file of type ,or list the first file of type?

### ISSUE THREAD

**Issue by nabileisa** [quentinrossetti/node-7z#90]
Hi , thanks for the great work on this library
I have been experimenting with it within an electron app and so far it's been great but I have hit a wall
**let's say I have an archive that contain a list of images and I want to extract only the first image found in the archive, is there a way to do that?**
I know that you can do that if you have the file name using `$cherryPick` , but I don't , which leads to my second question , I know you could use the `Seven.list()` method to get the all file names but that return the the names of all files as a stream if I understand correctly and I only need the first , so my second question is **Is there a way to get the name of the first file only ?**
thanks

**Comment by quentinrossetti** [comment]
Hi. I don't think it's possible. But it has more to do with the archives. Depending on the algorithm the order in which files are treated is kind of random.
I struggle to find a use case for your demand. What are you trying to achieve ?

**Comment by nabileisa** [comment]
Thanks for the reply
What I  am trying to to achieve is generate a list of thumbnail images from a list of archives.
I'm attempting to build a comic book library application that reads a list of archives , and extract the first image from each archive and resize it and save it for display in the library.
I'm currently able to do it using something like this
```
for (let i = 0; i < archiveList; i++) {
    let firstImg;
    const listStream = Seven.list(archiveList[i], {
        $cherryPick: ["*.png", "*.jpg", , "*.jpeg", "*.webp"],
    })
    listStream.on('data', data => {
        // set firstImg to the first result
        if (!firstImg) firstImg = data;
    })
    listStream.on('end', () => { 
        if (firstImg) {
            const extractStream = Seven.extract(file.path, tempFolder, {
                $cherryPick: firstImg.file,
            });
            extractStream.on('data', data => {
                //do something with the image
            })
        }
    })
}
```
And it works for the most part although it is a little slow because of the use of `Seven.List()` on each archive and wait for it to end before each extraction (I think).
what I was wondering about is if there was a better more performant way to do it , as I'm a beginner when it come to Nodejs and electron.

**Comment by quentinrossetti** [comment]
If you can't control how the archives are created or if there is no naming convention I think you are on the right path. Maybe try to extract instead of list, and remove the unwanted files ? (Do some tests for performance).
But if there is a naming convention in the archives you can simply the process (and probably other things in your app).
Happy coding !
