### ISSUE TITLE
Only extract specific file(s)

### ISSUE THREAD

**Issue by justin-dx** [quentinrossetti/node-7z#92]
How can I extract only specific files?
The command line switches using just 7z is `7z e [archive.zip] -o [outputdir] [fileFilter]`

```
const extractStream = extractFull('./archive.7z', './tmp/', {
    password: password,
    $bin: pathTo7zip,
    //$raw: ['-o./tmp/', 'x.jpg']
    //outputDir: `${outputFolderPath} x.jpg`
});
```
I've tried the above, but the extract does all files instead of just `x.jpg`.

**Comment by adamflorizone** [comment]
Try This:

```
const Seven = require('node-7z');

const myStream = Seven.extract('./test.7z', 'test', {
	$cherryPick: 'test.txt', // The file that you want
	toStdout: true, // This is the important part
});
myStream._childProcess.stdout.on("data",function(chunk) { // Chunk is a Buffer
	console.log(chunk.toString()); // this will print a Buffer object so you have to .tosting
});
```

Tested working:
```
nodejs test.js 
Hello World!

````

_Please note: _childProcess is exposed as private, and the name could change down the road. There should a public access point for _childProcess implemented  by the developers._

**Comment by justin-dx** [comment]
Thanks @adamflorizone that worked 👍
