### ISSUE TITLE
Garbled encoding with two or more byte UTF-8 encoding filenames

### ISSUE THREAD

**Issue by LazyLZ** [quentinrossetti/node-7z#93]
When list content of archives, there is a small probability that some file names are garbled: 

```
file: '中��码'
```

and the correct file name is:

```
file: '中文编码'
```

I read the source code and find that is because in `lines.js`, the buffer from stdout is directly encoding with UTF-8 using `bufer.toString()`, the uncomplete line is store in `_lastLinePartial` and concat with next buffer's first line:

```javascript
const fromBuffer = (seven, buffer) => {
  const lines = buffer.toString().split(LINE_SPLIT)
  if (seven._lastLinePartial) {
    lines[0] = seven._lastLinePartial.concat(lines[0])
  }
  const newLastLine = lines[lines.length - 1]
  const isNewLastLineComplete = (newLastLine.indexOf('\n') === newLastLine.length - 1)
  if (!isNewLastLineComplete) {
    seven._lastLinePartial = newLastLine
    lines.pop()
  } else {
    delete seven._lastLinePartial
  }
  return lines
}
```

The problem with this is that the buffer's last byte may not be a complete character because UTF-8 code can be one to four bytes.

So when it happens to be in the filename with non-ASCII characters, the `_lastLinePartial`'s last character and the first character of the next buffer's first line will all encoding to  `�`, as shown in the example above.

One possible solution is to store the incomplete line as buffer instead of string:

```javascript
const fromBuffer = (seven, buffer) => {
  if (seven._lastLinePartial) {
    buffer = Buffer.concat([seven._lastLinePartial, buffer])
  }
  const lines = buffer.toString().split(LINE_SPLIT)
  const offset = buffer.lastIndexOf('\n') + 1
  const newLastLine = buffer.slice(offset)
  const isNewLastLineComplete = (newLastLine.indexOf('\n') === newLastLine.length - 1)
  
  if (!isNewLastLineComplete) {
    seven._lastLinePartial = newLastLine
    lines.pop()
  } else {
    delete seven._lastLinePartial
  }
  return lines
}
```

By the way, is there possible to support `-slt` (techInfo) option in the `list` command?

**Comment by quentinrossetti** [comment]
Hello,
Thank you for reporting and for suggesting a solution ! I will work on the fix and the missing switch in the next few weeks.

**Comment by quentinrossetti** [comment]
So I feel like an update is due.
Day job is crazy at the moment !

The official 7z build for linux has been released and I'm focussing on the startegy to make it work.

The `slt ` switch is already supposed but in my testing (2 years ago) I remember that it didn't give more info on linux.the investigation continues.

**Comment by quentinrossetti** [comment]
Your code has been added, I passes the 200 mocha test with flying colors ! (well mainly green :) )
Indeed `-slt` needs some more work. I open an issue for that.
