### ISSUE TITLE
Not working with .wim archives

### ISSUE THREAD

**Issue by aleksey-hoffman** [quentinrossetti/node-7z#98]
Good day @quentinrossetti 

When trying to extract `wim` archive, nothing happens:

```js
const binExtractStream = node7z.extractFull(
  'E:/test/1.wim',
  'E:/test/output',
  {
    $bin: pathTo7ZipBin,
    $progress: true
  }
)

binExtractStream .on('error', (error) => {
  console.log(error)
})

binExtractStream .on('end', () => {
  console.log('success')
})
```

The `error` handler is not showing anything. The `end` handler runs successfully.

I'm specifying 7zip binary that supports wim archives. I tested it with node and it's extracting the file successfully:

```js
childProcess.execSync(`${pathTo7ZipBin} x "E:/test/1.wim" -o"E:/test/output" -bsp1 -y`)
```

**Comment by quentinrossetti** [comment]
Hi @aleksey-hoffman 
I'm a bit late to the party sorry :) 
For future reference do you remember how you fix it?

**Comment by aleksey-hoffman** [comment]
Hi @quentinrossetti I think it was a mistake on my part. I'm not sure why it wasn't working when I was testing it in my app. 
The module seems to be working with all supported formats now.
